apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: prod
  labels:
    app: booking-opt-frontend
spec:
  type: LoadBalancer         # Exposes nginx externally via a cloud LB
  selector:
    app: booking-opt-frontend
  ports:
  - name: http
    protocol: TCP
    port: 80                  # External port
    targetPort: 80            # Container port