apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bookingopt-ingress
  namespace: prod
  annotations:
    kubernetes.io/ingress.class: "gce"  # Use GKEâ€™s GCE ingress controller
spec:
  rules:
  - http:
      paths:
      - path: /api/
        pathType: Prefix
        backend:
          service:
            name: backend-service  # Matches backend-service.yaml
            port:
              number: 80
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend-service # Matches frontend-service.yaml
            port:
              number: 80